
export const LOCAL_STORAGE_KEYS = {
  RECIPES: 'RECIPES'
};


export const ARRAY_KEYS = {
  LABEL: 'LABEL',
  VALUE: 'VALUE',
  COMPONENT: 'COMPONENT',
  DATA: 'DATA',
  ON_CLICK: 'ON_CLICK',
  HEADER: 'HEADER',
  BODY: 'BODY',
  DISPLAY_FN: 'DISPLAY_FN',
  MIN_WIDTH: 'MIN_WIDTH',
  MAX_WIDTH: 'MAX_WIDTH'
};
